package com.kingdom.menumate.Database;

import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

public class DatabaseHelper extends SQLiteOpenHelper {
    public static final String DB_NAME = "restaurant";
    public static final int DB_VERSION = 1;

    public static final String ID = "id";
    public static final String NAME = "name";
    public static final String DESCRIPTION = "description";
    public static final String IMAGE_URL = "image_url";
    public static final String PRICE = "price";
    public static final String CATEGORY = "category";

    public static final String CATEGORIES = "categories";
    public static final String FOODS = "foods";

    public DatabaseHelper(@Nullable Context context) {
        super(context, DB_NAME, null, DB_VERSION);
    }


    @Override
    public void onCreate(SQLiteDatabase sqLiteDatabase) {
        String createCategoriesTable = "CREATE TABLE " + CATEGORIES + " (" + ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " + NAME + " TEXT, " + IMAGE_URL + " TEXT);";
        String createFoodsTable = "CREATE TABLE " + FOODS + " (" + ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " + NAME + " TEXT, " + DESCRIPTION + " TEXT, " + PRICE + " TEXT, " + IMAGE_URL + " TEXT, " + CATEGORY + " TEXT);";
        sqLiteDatabase.execSQL(createCategoriesTable);
        sqLiteDatabase.execSQL(createFoodsTable);

        initCategoriesData(sqLiteDatabase);
        initFoodsData(sqLiteDatabase);
    }

    private void insertIntoCategories(SQLiteDatabase sqLiteDatabase, String name, String image_url) {
        ContentValues values = new ContentValues();
        values.put(NAME, name);
        values.put(IMAGE_URL, image_url);
        sqLiteDatabase.insert(CATEGORIES, null, values);
    }

    private void insertIntoFoods(SQLiteDatabase sqLiteDatabase, String name, String description, String price, String image_url, String category) {
        ContentValues values = new ContentValues();
        values.put(NAME, name);
        values.put(DESCRIPTION, description);
        values.put(PRICE, price);
        values.put(IMAGE_URL, image_url);
        values.put(CATEGORY, category);
        sqLiteDatabase.insert(FOODS, null, values);
    }

    private void initCategoriesData(SQLiteDatabase sqLiteDatabase) {
        insertIntoCategories(sqLiteDatabase, "Appetizers", "https://static.onecms.io/wp-content/uploads/sites/44/2019/08/27044817/6753427.jpg");
        insertIntoCategories(sqLiteDatabase, "Soups", "https://www.seriouseats.com/thmb/gTjuNwNldf0o7ns_86w9Dgtvp3U=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2017__02__20170111-pressure-cooker-beef-barley-soup-vicky-wasik-13-84001c6817584d2cb7d5dd14b12d405d.jpg");
        insertIntoCategories(sqLiteDatabase, "Salads", "https://www.seriouseats.com/thmb/M8yuFyaR41ytfymsNCFR8NpJKCo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__images__2016__04__20131009-caesar-salad-food-lab-11-Edit-bf19618057e34330b55723e191a5aa49.jpg");
        insertIntoCategories(sqLiteDatabase, "Sandwiches", "https://www.seriouseats.com/thmb/XCdWMlszNKlJH98Mb09n37ACrzU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__images__2017__05__20170501-sandwich-recipe-roundup-01-01203a6950b64f3d84683c6f8a8ffa2e.jpg");
        insertIntoCategories(sqLiteDatabase, "Burgers", "https://www.seriouseats.com/thmb/EksgIbEhh6Q1vHU3OdeSXdvlVek=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/20210607-CLASSICSMASHEDBURGS-JANJIGIAN-seriouseats-10-8af40a4a1698459c99e7f3c0df7f6a0f.jpg");
        insertIntoCategories(sqLiteDatabase, "Tacos", "https://www.seriouseats.com/thmb/8R8vWWxn19sVwz_4VaiNouQvU3g=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__images__2013__04__20130427-tacos-al-pastor-new-01-afe3f8dee38647ddb91b0db02a965425.jpg");
        insertIntoCategories(sqLiteDatabase, "Pizza", "https://www.seriouseats.com/thmb/hk2H7N1wmRwR0-x0Rz5r3Ef6Zz8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/2016__05__20160503-Uuni-oven-pizza-review--b75c5ec340ea4b5f9587a9da3201884b.jpg");
        insertIntoCategories(sqLiteDatabase, "Seafoods", "https://www.seriouseats.com/thmb/Knbd5RJKVlMSJoA9LSYg9vK3HuY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2015__06__20150622-jalea-fried-seafood-peruvian-vicky-wasik-15-2f5d1581681f4b548b37d2af9bb92dc8.jpg");
        insertIntoCategories(sqLiteDatabase, "Steaks", "https://www.seriouseats.com/thmb/SPwqliMDj-ZqwpHGj6PHXkPyJAg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__images__2015__04__Anova-Steak-Guide-Sous-Vide-Photos15-beauty-736633d3c3374147b8e1a78194e95dda.jpg");
        insertIntoCategories(sqLiteDatabase, "Pastas", "https://www.seriouseats.com/thmb/9HihhYeHwnvdF_mmt3ULEXJ7hj4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2021__02__20210218-burro-e-alici-sasha-marx-11-d30e7f3153414346a24169785e1ffe41.jpg");
        insertIntoCategories(sqLiteDatabase, "Chicken", "https://www.seriouseats.com/thmb/aqnh37dRljSaeJQoGS7wK-4Yg6Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__images__2015__06__20150610-sous-vide-chicken-guide-36-764d00a5cb1c44f7a9b60f16b0e1c6ef.jpg");
        insertIntoCategories(sqLiteDatabase, "Vegetarian", "https://www.seriouseats.com/thmb/Q3AsW1LL1JALEfU-oXS_b7cZZ6Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2014__04__20140403-new-vegetarian-cooking-for-everyone-spicy-tofu-bc5913b4d9644a5aba2cda32b559fa93.jpg");
        insertIntoCategories(sqLiteDatabase, "Vegan", "https://www.seriouseats.com/thmb/AdPuHcJUUfHTTDJDqhTK-yJyzFg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2016__03__20160319-vegan-menemen-recipe-5-1605208265bd494dae91c448361f9066.jpg");
        insertIntoCategories(sqLiteDatabase, "Gluten-Free", "https://www.seriouseats.com/thmb/7RpBMG-uuhY3g6YNmhC9x0TpfYQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__images__2014__05__20140506-skirt-steak-polenta-cherry-tomato-easy-6-0ab5ef219fc145a6b42097e836ce6779.jpg");
        insertIntoCategories(sqLiteDatabase, "Breakfast", "https://www.mashed.com/img/gallery/popular-chain-breakfast-restaurants-ranked-worst-to-best-upgrade/intro-1653347360.jpg");
        insertIntoCategories(sqLiteDatabase, "Lunch", "https://media-cdn.tripadvisor.com/media/photo-s/16/62/37/d2/magic-foods.jpg");
        insertIntoCategories(sqLiteDatabase, "Dinner", "https://www.thejosie.com/wp-content/uploads/2019/12/Dinner-horz-1024x768.jpg");
        insertIntoCategories(sqLiteDatabase, "Brunch", "https://images.squarespace-cdn.com/content/v1/56a2785c69a91af45e06a188/1559149420983-ZG7GUZY6VFWVPDJL369P/Restaurant-Brunch-ReinventMenu.png");
        insertIntoCategories(sqLiteDatabase, "Drinks", "https://cdn.winsightmedia.com/platform/files/public/2017-11/background/600x450/fruity-drinks-cocktails_1510587040.jpg");
        insertIntoCategories(sqLiteDatabase, "Desserts", "https://www.pjponline.com/wp-content/uploads/2019/02/shutterstock_475360618-1024x683.jpg");
        insertIntoCategories(sqLiteDatabase, "Kids Menu", "https://cdn.vox-cdn.com/thumbor/Po2tQ26dcB20LaPQzzw26N3B5Jg=/0x0:4288x2848/1200x800/filters:focal(1801x1081:2487x1767)/cdn.vox-cdn.com/uploads/chorus_image/image/55855587/chicken_tenders.0.jpg");
    }

    private void initFoodsData(SQLiteDatabase sqLiteDatabase) {
        insertIntoFoods(sqLiteDatabase, "Fried Calamari", "Lightly breaded and fried calamari served with a zesty marinara sauce.", "$9.99", "https://www.thespruceeats.com/thmb/mSSesN51fxcSw9989PPvtA-nMyk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/fried-calamari-2019531-hero-01-e294f265d7e84c0f89d4b5759759ffbf.jpg", "Appetizers");
        insertIntoFoods(sqLiteDatabase, "Bruschetta", "Grilled bread topped with fresh tomatoes, garlic, basil, and drizzled with balsamic glaze.", "$7.99", "https://www.thespruceeats.com/thmb/ebstnNM4bXINCIsrReahhsEqy3Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/fresh-tomato-and-basil-bruschetta-2238401_hero_01-a5a087252af045c2813a166ceac39a54.jpg", "Appetizers");
        insertIntoFoods(sqLiteDatabase, "Mozzarella Sticks", "Golden brown fried mozzarella sticks served with marinara sauce for dipping.", "$6.99", "https://sugarspunrun.com/wp-content/uploads/2021/07/Homemade-Mozzarella-Sticks-Recipe-1-of-1.jpg", "Appetizers");
        insertIntoFoods(sqLiteDatabase, "Chicken Wings", "Crispy chicken wings tossed in your choice of sauce (buffalo, honey mustard, BBQ, or teriyaki).", "$8.99", "https://www.thespruceeats.com/thmb/NE91zSEOtMIdysU9TtaRF1lfFZE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/barbecue-chicken-wings-18-gt-56a8ba4f5f9b58b7d0f4a234.jpg", "Appetizers");
        insertIntoFoods(sqLiteDatabase, "Shrimp Cocktail", "Jumbo shrimp served with a tangy cocktail sauce and lemon wedge.", "$10.99", "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2004/4/21/0/bw2b09_shrimp_cocktail.jpg.rend.hgtvcom.616.462.suffix/1557928675507.jpeg", "Appetizers");

        insertIntoFoods(sqLiteDatabase, "Chicken Noodle Soup", "Classic soup made with tender chicken, egg noodles, and fresh vegetables in a savory chicken broth. Served with crackers.", "$5.99", "https://www.thespruceeats.com/thmb/R3JSiJn_l8atbwsEBkqQ0e5sSIQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/instant-pot-chicken-noodle-soup-recipe-4771904-main-560c1ea8c83547b097be9d81b756636f.jpg", "Soups");
        insertIntoFoods(sqLiteDatabase, "Tomato Basil Soup", "Rich and creamy tomato soup blended with fresh basil and topped with a dollop of sour cream. Served with garlic bread.", "$4.99", "https://www.thespruceeats.com/thmb/UNrF3es22PQcgjuUiKBCaPGG_wY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/tomato-basil-soup-2246275-hero-01-af8c4e4119524f0199f37857c57db2bf.jpg", "Soups");
        insertIntoFoods(sqLiteDatabase, "Minestrone Soup", "A hearty Italian vegetable soup with tomatoes, beans, carrots, celery, and pasta. Served with garlic bread.", "$6.99", "https://www.thespruceeats.com/thmb/buhBQ2wPXomwRg15TGIHyzS9ZR4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/vegetarian-minestrone-soup-recipe-3378002-4-4-5b0daf07ff1b7800364adfa4.jpg", "Soups");
        insertIntoFoods(sqLiteDatabase, "Clam Chowder", "Creamy New England style chowder made with fresh clams, potatoes, onions, and celery. Served with oyster crackers.", "$7.99", "https://www.thespruceeats.com/thmb/nkveivzfiqKr8eOn61vmzSKJXY8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/manhattan-clam-chowder-sc-15-56a8ba0c5f9b58b7d0f4a191.jpg", "Soups");
        insertIntoFoods(sqLiteDatabase, "French Onion Soup", "Sweet caramelized onions in a rich beef broth topped with toasted French bread and melted Swiss cheese.", "$8.99", "https://www.thespruceeats.com/thmb/OB1PLDaSaH45Hs2uzAN5kOLsO44=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/easy-french-onion-soup-3062131-hero-01-2a93bd3c60084db5a8a8e1039c0e0a2f.jpg", "Soups");

        insertIntoFoods(sqLiteDatabase, "Caesar Salad", "Crisp romaine lettuce, shaved Parmesan cheese, and homemade croutons tossed in a classic Caesar dressing.", "$8.99", "https://www.thespruceeats.com/thmb/NW5YtbUK-wnR6RNNYOkEGyIySJE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/classic-caesar-salad-recipe-996054-Hero_01-33c94cc8b8e841ee8f2a815816a0af95.jpg", "Salads");
        insertIntoFoods(sqLiteDatabase, "Greek Salad", "Mixed greens, cucumber, red onion, tomato, Kalamata olives, and feta cheese tossed in a lemon vinaigrette.", "$9.99", "https://www.thespruceeats.com/thmb/apk0_GF6pUj92OEoHOEq4isLzH4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/classic-greek-salad-3964419-hero-01-15afcdaddaa242aaa788f358ab9ca7d9.jpg", "Salads");
        insertIntoFoods(sqLiteDatabase, "Cobb Salad", "Grilled chicken breast, avocado, hard-boiled egg, bacon, tomato, and blue cheese crumbles served over mixed greens with choice of dressing.", "$12.99", "https://www.thespruceeats.com/thmb/QD34ouhSUij5XSja5Ez4DO9q7h0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/classic-cobb-salad-recipe-100890-hero-01-3a162efa1df943b79d110c832281f652.jpg", "Salads");
        insertIntoFoods(sqLiteDatabase, "Caprese Salad", "Fresh mozzarella cheese, tomato, and basil drizzled with balsamic glaze and olive oil.", "$7.99", "https://www.thespruceeats.com/thmb/-ivBI4jtdbxQWqOjimdJVi-OF2g=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/caprese-salad-tomato-salad-2217097-hero-03-75a0b89b30aa4a52b10fe4fdd9abfeb5.jpg", "Salads");
        insertIntoFoods(sqLiteDatabase, "Spinach Salad", "Baby spinach, sliced strawberries, red onion, candied pecans, and goat cheese served with raspberry vinaigrette.", "$10.99", "https://www.thespruceeats.com/thmb/Sw7ygRB2F0H-Az7f1UU7HsdACng=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/spinach-salad-155386822-56a8c61c3df78cf772a07c43.jpg", "Salads");

        insertIntoFoods(sqLiteDatabase, "The Classic Club", "Roasted turkey breast, crisp bacon, lettuce, tomato, and mayo on your choice of bread.", "$9.99", "https://www.thespruceeats.com/thmb/auKH15ImwKCnnH3BuRKFSi6GuZ4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/turkey-club-sandwich-recipe-996062-hero-5c252e0346e0fb0001abeaea.jpg", "Sandwiches");
        insertIntoFoods(sqLiteDatabase, "Reuben", "Thinly sliced corned beef, sauerkraut, Swiss cheese, and thousand island dressing on grilled rye bread.", "$10.99", "https://www.thespruceeats.com/thmb/Sx8NA4NfQvO5EpSdJkvRQM-eqy0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/preparing-a-reuben-sandwich-184271755-56ea99ec3df78cb4b97bb599.jpg", "Sandwiches");
        insertIntoFoods(sqLiteDatabase, "Philly Cheesesteak", "Shaved sirloin steak, sautéed onions and peppers, and melted provolone cheese on a toasted hoagie roll.", "$11.99", "https://unpeeledjournal.com/wp-content/uploads/2021/06/51247288001_ba2ce0ad6c_h-1-500x500.jpg", "Sandwiches");
        insertIntoFoods(sqLiteDatabase, "Veggie Wrap", "Grilled portobello mushrooms, roasted red peppers, zucchini, squash, and goat cheese wrapped in a spinach tortilla.", "$8.99", "https://upload.wikimedia.org/wikipedia/commons/f/f8/Smoked_chicken_and_avocado_wrap.jpg", "Sandwiches");
        insertIntoFoods(sqLiteDatabase, "Grilled Cheese", "Melted American and cheddar cheese on your choice of bread. Served with a side of tomato soup.", "$7.99", "https://www.thespruceeats.com/thmb/OP77SUyWxuQXd8Enm9k6jQClT6Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/garlic-bread-grilled-cheese-4687223-hero-03-d4bb5c01c2894945a80ceb63062555c4.jpg", "Sandwiches");

        insertIntoFoods(sqLiteDatabase, "The Classic Burger", "A juicy beef patty, lettuce, tomato, and onion on a toasted bun.", "$10.99", "https://www.thespruceeats.com/thmb/6gYgwlfzbggdckI196HWvT2qVgc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/homemade-impossible-burger-4801190-07-90a9b58380f541e6a8d49c7d5b99a1e2.jpg", "Burgers");
        insertIntoFoods(sqLiteDatabase, "Bacon Cheeseburger", "A classic burger topped with crispy bacon and melted cheddar cheese.", "$12.99", "https://www.simplyrecipes.com/thmb/cgJTtVSTy-ftI1dBM4P2x2FJf14=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Bacon-Cheeseburger-LEAD-2b-6606850da0164612b5fb406a0e33f8df.jpg", "Burgers");
        insertIntoFoods(sqLiteDatabase, "Mushroom Swiss Burger", "A juicy beef patty topped with sautéed mushrooms and melted Swiss cheese on a toasted bun.", "$11.99", "https://bestbeefrecipes.com/wp-content/uploads/2020/07/mushroom-swiss-burger-2.jpg", "Burgers");
        insertIntoFoods(sqLiteDatabase, "Veggie Burger", "A grilled veggie patty topped with lettuce, tomato, and onion on a toasted bun.", "$9.99", "https://www.thespruceeats.com/thmb/O3nMam_8aNjdS4HboKQZOaPKegk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-998869152-5bdfb1e64cedfd002673da55.jpg", "Burgers");
        insertIntoFoods(sqLiteDatabase, "BBQ Burger", "A juicy beef patty topped with crispy onion rings, tangy BBQ sauce, and cheddar cheese on a toasted bun.", "$13.99", "https://recipes.net/wp-content/uploads/2021/10/the-best-grilled-bbq-burger-recipe.jpg", "Burgers");

        insertIntoFoods(sqLiteDatabase, "Beef Tacos", "Three soft shell tacos with seasoned ground beef, lettuce, tomato, shredded cheese, and sour cream. Served with salsa and chips.", "$9.99", "https://www.thespruceeats.com/thmb/AWP8ACQLHEe2xmMWkCBlGmmWqZk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Softbeeftacos-GettyImages-614313140-593df4533df78c537b375d6d.jpg", "Tacos");
        insertIntoFoods(sqLiteDatabase, "Fish Tacos", "Three crispy fish tacos with cabbage slaw, pico de gallo, and chipotle sauce. Served with a side of black beans and rice.", "$11.99", "https://www.thespruceeats.com/thmb/y5wzEfVpxkhy5TWqPDPftbi1Z94=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/tilapia-fish-tacos-14-6c62d849f2c146ebade8470686940baa.jpg", "Tacos");
        insertIntoFoods(sqLiteDatabase, "Shrimp Tacos", "Three grilled shrimp tacos with avocado, cilantro, and lime crema. Served with a side of black beans and rice.", "$12.99", "https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2020/04/Shrimp-Tacos-main-1.jpg", "Tacos");
        insertIntoFoods(sqLiteDatabase, "Chicken Tinga Tacos", "Three shredded chicken tacos with chipotle sauce, avocado, and cilantro. Served with a side of refried beans and rice.", "$10.99", "https://www.foodandwine.com/thmb/c92HkN62irUE_081_rqub5y0EfA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/201112-xl-chicken-tinga-tacos-c366d8b884f447e3822455f1b03009e5.jpg", "Tacos");
        insertIntoFoods(sqLiteDatabase, "Veggie Tacos", "Three vegetarian tacos with roasted mushrooms, peppers, onions, and zucchini. Served with salsa and chips.", "$8.99", "https://www.simplyrecipes.com/thmb/Vw6TDXD2gW87OU1PNWPfNsKaD84=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Veggie-Tacos-LEAD-2-2fa9781c94da4b9797af48af47313854.jpg", "Tacos");

        insertIntoFoods(sqLiteDatabase, "Margherita", "Fresh mozzarella cheese, San Marzano tomatoes, and basil.", "$12.99", "https://www.foodandwine.com/thmb/3kzG4PWOAgZIIfZwMBLKqoTkaGQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/margherita-pizza-with-argula-and-prosciutto-FT-RECIPE0721-04368ec288a84d2e997573aca0001d98.jpg", "Pizza");
        insertIntoFoods(sqLiteDatabase, "Pepperoni", "Classic pepperoni pizza with tomato sauce and mozzarella cheese.", "$14.99", "https://www.thespruceeats.com/thmb/Ql0AbohU4EvfbfiWqXOwnePxTP8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Pepperonipizzahoriz-3d53b00a7cce429eae3bfb629df356ec.jpg", "Pizza");
        insertIntoFoods(sqLiteDatabase, "Hawaiian", "Ham, pineapple, and mozzarella cheese.", "$13.99", "https://www.thespruceeats.com/thmb/2lT2bHjV5ok82eiy3wX-eREGIW0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/hawaiian-pizza-4691857-hero-01-1a8f6764c70e4113bbf31bd1a73aca2e.jpg", "Pizza");
        insertIntoFoods(sqLiteDatabase, "Meat Lover's", "Pepperoni, sausage, ham, and bacon with tomato sauce and mozzarella cheese.", "$16.99", "https://www.queensleeappetit.com/wp-content/uploads/2019/02/Meat-Lovers-Pizza-5-1-480x480.jpg", "Pizza");
        insertIntoFoods(sqLiteDatabase, "Veggie", "Mushrooms, onions, peppers, black olives, and mozzarella cheese.", "$12.99", "https://www.twopeasandtheirpod.com/wp-content/uploads/2021/03/Veggie-Pizza-8.jpg", "Pizza");

        insertIntoFoods(sqLiteDatabase, "Lobster Roll", "Chilled Maine lobster tossed in lemon aioli, served on a buttered and grilled brioche roll.", "$19.99", "https://www.simplyrecipes.com/thmb/sGLLVhhk2WcGYQHOHPpSKgUEomA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2020__07__New-England-Lobster-Rolls-LEAD-3b-66e6d533de5643f5b00f40aa9e9c8251.jpg", "Seafoods");
        insertIntoFoods(sqLiteDatabase, "Crab Cakes", "Pan-seared crab cakes served with remoulade sauce and lemon wedges.", "$17.99", "https://grandbaby-cakes.com/wp-content/uploads/2020/02/Crab-cakes-3.jpg", "Seafoods");
        insertIntoFoods(sqLiteDatabase, "Grilled Shrimp Skewers", "Grilled shrimp skewers marinated in garlic and lemon served over a bed of rice.", "$15.99", "https://feelgoodfoodie.net/wp-content/uploads/2020/05/Grilled-Shrimp-Skewers-6.jpg", "Seafoods");
        insertIntoFoods(sqLiteDatabase, "Fish and Chips", "Crispy beer-battered cod served with fries, coleslaw, and tartar sauce.", "$14.99", "https://www.thespruceeats.com/thmb/n-QHxbubDjqDFeeQkUCA5QZDmsI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/best-fish-and-chips-recipe-434856-Hero-5b61b89346e0fb00500f2141.jpg", "Seafoods");
        insertIntoFoods(sqLiteDatabase, "Cioppino", "Italian fisherman's stew with assorted seafood, tomatoes, and herbs served with grilled bread.", "$22.99", "https://www.thespruceeats.com/thmb/nJ8ZUxa0G9yqY3DPNb9Ks7oMU1g=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-sbossert-490287432-92e085d118674aeda18c0b63afe76eec.jpg", "Seafoods");

        insertIntoFoods(sqLiteDatabase, "Filet Mignon", "8 oz. hand-cut tenderloin, seasoned and grilled to perfection. Served with a baked potato and seasonal vegetables.", "$28.99", "https://www.thespruceeats.com/thmb/5a4CGFNo6DjjHcsYNYk6NA4Ro-o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/DSC_7371-589dd3025f9b58819c85d5ee.JPG", "Steaks");
        insertIntoFoods(sqLiteDatabase, "Ribeye", "12 oz. hand-cut ribeye, seasoned and grilled to perfection. Served with garlic mashed potatoes and seasonal vegetables.", "$24.99", "https://www.thespruceeats.com/thmb/ev6hrW6peELELCnpbrVO1DCgGcI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/rib-eye-roast-recipe-3058676-hero-01-2302304fd0e746a09d284c81df3da6a8.jpg", "Steaks");
        insertIntoFoods(sqLiteDatabase, "New York Strip", "10 oz. hand-cut strip steak, seasoned and grilled to perfection. Served with a loaded baked potato and seasonal vegetables.", "$26.99", "https://therecipecritic.com/wp-content/uploads/2021/01/newyorkstripsteak.jpg", "Steaks");
        insertIntoFoods(sqLiteDatabase, "Prime Rib", "Slow roasted prime rib, served with horseradish sauce, garlic mashed potatoes, and seasonal vegetables.", "$27.99", "https://www.thespruceeats.com/thmb/Fk4sHz-Dtga9rma8HAXlGlVg4-Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/deep-fried-prime-rib-4154327-hero-01-ff8f58e6d7ff47c8b3bbcb6fa048f82a.jpg", "Steaks");
        insertIntoFoods(sqLiteDatabase, "Surf and Turf", "8 oz. filet mignon paired with a 6 oz. lobster tail. Served with a baked potato and seasonal vegetables.", "$34.99", "https://natashaskitchen.com/wp-content/uploads/2022/02/Surf-and-Turf-Steak-and-Shrimp-SQ.jpg", "Steaks");

        insertIntoFoods(sqLiteDatabase, "Spaghetti and Meatballs", "Classic spaghetti served with homemade meatballs in a rich tomato sauce.", "$12.99", "https://www.thespruceeats.com/thmb/qA23NI1AhG2pcLZtQZZcQDjlnq4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/spaghettimeatballs-135583313-56bdcea15f9b5829f85ee94a.jpg", "Pastas");
        insertIntoFoods(sqLiteDatabase, "Fettuccine Alfredo", "Creamy Alfredo sauce served with fettuccine noodles.", "$10.99", "https://www.thespruceeats.com/thmb/4_riVwbKbbMABgL244f67fRvIQs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/crockpot-chicken-alfredo-479568-13_preview-5aff432cfa6bcc0036ee9590.jpeg", "Pastas");
        insertIntoFoods(sqLiteDatabase, "Penne alla Vodka", "Penne pasta tossed in a creamy tomato vodka sauce with Parmesan cheese.", "$13.99", "https://www.thespruceeats.com/thmb/0yLl01bjNd2klnob2PutAn_WIUw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/one-pot-penne-alla-vodka-4133615-hero-01-9f83e23d728b4c62a35f6706abb70f0b.jpg", "Pastas");
        insertIntoFoods(sqLiteDatabase, "Lobster Ravioli", "Fresh ravioli stuffed with lobster and served in a creamy tomato sauce.", "$16.99", "https://www.chiselandfork.com/wp-content/uploads/2020/07/lobster-ravioli-1.jpg", "Pastas");
        insertIntoFoods(sqLiteDatabase, "Pesto Linguine", "Linguine noodles tossed in a basil pesto sauce with sun-dried tomatoes and Parmesan cheese.", "$14.99", "https://www.onceuponachef.com/images/2020/08/Linguine-with-Creamy-Arugula-Walnut-Pesto-scaled.jpg", "Pastas");

        insertIntoFoods(sqLiteDatabase, "Classic Fried Chicken", "Crispy fried chicken served with mashed potatoes, gravy, and green beans.", "$12.99", "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/6/3/1/FNM_070111-Fried-Chicken-026_s4x3.jpg.rend.hgtvcom.616.462.suffix/1382539796174.jpeg", "Chicken");
        insertIntoFoods(sqLiteDatabase, "Grilled Chicken Caesar Salad", "Grilled chicken breast served on a bed of fresh romaine lettuce with Caesar dressing and croutons.", "$10.99", "https://thewoodenskillet.com/wp-content/uploads/2021/08/grilled-chicken-caesar-salad-recipe-1.jpg", "Chicken");
        insertIntoFoods(sqLiteDatabase, "Chicken Parmesan", "Breaded chicken breast topped with marinara sauce and melted mozzarella cheese. Served with spaghetti.", "$14.99", "https://assets.bonappetit.com/photos/5ea8f0df16738800085ad5d2/1:1/w_2560%2Cc_limit/Chicken-Parmesean-Recipe-Lede.jpg", "Chicken");
        insertIntoFoods(sqLiteDatabase, "Honey Mustard Chicken Wrap", "Grilled chicken, lettuce, tomato, and honey mustard sauce wrapped in a spinach tortilla.", "$9.99", "https://taoofspice.com/wp-content/uploads/2022/05/Stack-of-honey-mustard-chicken-wraps-surrounded-by-parsley-and-a-spoon-dripping-with-honey-mustard.-720x720.jpg", "Chicken");
        insertIntoFoods(sqLiteDatabase, "Chicken Alfredo", "Grilled chicken breast tossed in a creamy Alfredo sauce with fettuccine pasta.", "$13.99", "https://bellyfull.net/wp-content/uploads/2021/02/Chicken-Alfredo-blog-4-768x1024.jpg", "Chicken");

        insertIntoFoods(sqLiteDatabase, "Mushroom Risotto", "Creamy arborio rice cooked with mushrooms and parmesan cheese.", "$13.99", "https://www.allrecipes.com/thmb/Z-9epjljCrVDmekGjxT6yd0mbHc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/85389-gourmet-mushroom-risotto-84-883f9f67760d4fa09d3bc123639d6bde.jpg", "Vegetarian");
        insertIntoFoods(sqLiteDatabase, "Veggie Burger", "Homemade veggie patty made with black beans, mushrooms, and quinoa. Served with lettuce, tomato, and avocado on a brioche bun.", "$10.99", "https://www.thespruceeats.com/thmb/e-lll-PpJ5F-MF4C57LYag3IAB8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-vegan-black-bean-veggie-burgers-3377008-hero-05-f7c0f0d9865e48b6be52a4c76ee22438.jpg", "Vegetarian");
        insertIntoFoods(sqLiteDatabase, "Eggplant Parmesan", "Breaded eggplant slices layered with tomato sauce, mozzarella, and parmesan cheese. Served with spaghetti marinara.", "$14.99", "https://fitfoodiefinds.com/wp-content/uploads/2021/07/eggplant-parmesan-10-scaled.jpg", "Vegetarian");
        insertIntoFoods(sqLiteDatabase, "Spinach and Ricotta Stuffed Shells", "Jumbo pasta shells filled with a mixture of spinach and ricotta cheese. Baked with tomato sauce and mozzarella cheese.", "$12.99", "https://saltedmint.com/wp-content/uploads/2018/11/Easy-Spinach-and-Ricotta-Stuffed-Shells-4-of-7.jpg", "Vegetarian");
        insertIntoFoods(sqLiteDatabase, "Grilled Vegetable Panini", "Grilled zucchini, squash, eggplant, red peppers, and goat cheese on ciabatta bread.", "$9.99", "https://cook.fnr.sndimg.com/content/dam/images/cook/fullset/2011/12/5/0/CC-kelsey-nixon_grilled-vegetable-sandwich-recipe_s4x3.jpg.rend.hgtvcom.616.462.suffix/1416331590068.jpeg", "Vegetarian");

        insertIntoFoods(sqLiteDatabase, "Beyond Burger", "A vegan burger patty made from plant-based protein, served on a whole grain bun with lettuce, tomato, and pickles. Served with a side of sweet potato fries.", "$12.99", "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/beyond-burger-nutrition-and-ingredients-1569351590.jpg", "Vegan");
        insertIntoFoods(sqLiteDatabase, "Vegan Pad Thai", "Stir-fried rice noodles with tofu, bean sprouts, scallions, peanuts, and a sweet and savory sauce.", "$14.99", "https://pinchofyum.com/wp-content/uploads/Vegetarian-Pad-Thai-Recipe.jpg", "Vegan");
        insertIntoFoods(sqLiteDatabase, "Jackfruit Tacos", "Two soft tacos filled with jackfruit, avocado, salsa, and vegan sour cream. Served with a side of black beans and rice.", "$10.99", "https://veganhuggs.com/wp-content/uploads/2019/03/vegan-jackfruit-tacos-4-500x375.jpg", "Vegan");
        insertIntoFoods(sqLiteDatabase, "Vegan Mac and Cheese", "Elbow macaroni tossed in a creamy vegan cheese sauce made from cashews and nutritional yeast.", "$9.99", "https://daiyafoods.com/wp-content/uploads/2016/04/Mac-and-Cheez.jpg", "Vegan");
        insertIntoFoods(sqLiteDatabase, "Vegan Caesar Salad", "Crisp romaine lettuce tossed in a tangy vegan Caesar dressing and topped with croutons and vegan Parmesan cheese.", "$8.99", "https://static01.nyt.com/images/2020/01/02/dining/bh-vegan-caesar/bh-vegan-caesar-articleLarge.jpg", "Vegan");

        insertIntoFoods(sqLiteDatabase, "Quinoa Salad", "A fresh salad made with quinoa, mixed greens, cherry tomatoes, cucumber, red onion, and avocado. Served with a lemon vinaigrette.", "$9.99", "https://kristineskitchenblog.com/wp-content/uploads/2022/05/quinoa-salad-2.jpg", "Gluten-Free");
        insertIntoFoods(sqLiteDatabase, "Grilled Salmon", "A juicy salmon filet seasoned with lemon and herbs, and grilled to perfection. Served with a side of steamed vegetables.", "$16.99", "https://www.dinneratthezoo.com/wp-content/uploads/2019/05/grilled-salmon-final-2.jpg", "Gluten-Free");
        insertIntoFoods(sqLiteDatabase, "Caprese Pizza", "A delicious pizza topped with fresh mozzarella cheese, sliced tomato, and basil. Made with a gluten-free crust.", "$14.99", "https://static.onecms.io/wp-content/uploads/sites/19/2014/07/29/caprese-pizza-ck-x.jpg", "Gluten-Free");
        insertIntoFoods(sqLiteDatabase, "Grilled Chicken Breast", "A tender chicken breast grilled to perfection, seasoned with herbs and spices. Served with a side of roasted sweet potatoes.", "$12.99", "https://www.onceuponachef.com/images/2020/05/best-grilled-chicken-scaled.jpg", "Gluten-Free");
        insertIntoFoods(sqLiteDatabase, "Gluten-Free Pasta", "A classic pasta dish made with gluten-free pasta and a flavorful tomato sauce. Topped with grated Parmesan cheese.", "$11.99", "https://media.olivegarden.com/en_us/images/product/d-gluten-free-rotini-with-meat-sauce-dpv.jpg", "Gluten-Free");

        insertIntoFoods(sqLiteDatabase, "Classic Breakfast", "Two eggs any style, choice of bacon or sausage, hash browns, and toast.", "$9.99", "https://media-cdn.tripadvisor.com/media/photo-s/07/ed/19/e6/knowles-restaurant.jpg", "Breakfast");
        insertIntoFoods(sqLiteDatabase, "Pancakes", "Fluffy buttermilk pancakes served with butter and maple syrup.", "$8.99", "https://www.eggs.ca/assets/RecipePhotos/Fluffy-Pancakes-New-CMS.jpg", "Breakfast");
        insertIntoFoods(sqLiteDatabase, "French Toast", "Thick slices of brioche bread dipped in cinnamon vanilla batter and griddled golden brown. Served with butter and maple syrup.", "$10.99", "https://www.simplyrecipes.com/thmb/b48moNCTtaUYEc1Qyxhe9V66XKc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-French-Toast-Lead-Shot-3b-c3a68a576a9548f5bd43cce3d2d7f4b7.jpg", "Breakfast");
        insertIntoFoods(sqLiteDatabase, "Omelette", "Fluffy three-egg omelette with your choice of fillings. Served with hash browns and toast.", "$11.99", "https://www.simplyrecipes.com/thmb/LLhiA8KZ7JZ5ZI0g-1bF1eg-gGM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2018__10__HT-Make-an-Omelet-LEAD-HORIZONTAL-17cd2e469c4a4ccbbd1273a7cae6425c.jpg", "Breakfast");
        insertIntoFoods(sqLiteDatabase, "Eggs Benedict", "Two poached eggs on an English muffin with Canadian bacon and hollandaise sauce. Served with hash browns.", "$12.99", "https://www.allrecipes.com/thmb/Ez-D-Ee4lcdHAHlJzFAJHa-1DRM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/17205-eggs-benedict-beauty-2x1-BP-2830-9a9e88ae2fe745bc9549667c679af572.jpg", "Breakfast");

        insertIntoFoods(sqLiteDatabase, "Grilled Chicken Sandwich", "Grilled chicken breast with lettuce, tomato, and mayo on a toasted bun. Served with fries.", "$11.99", "https://thefamilydinnerproject.org/wp-content/uploads/2014/07/Easy-grilled-chicken-sandwich.jpg", "Lunch");
        insertIntoFoods(sqLiteDatabase, "Caesar Salad", "Romaine lettuce, croutons, and grated Parmesan cheese, with Caesar dressing. Add grilled chicken for $3.", "$9.99", "https://www.seriouseats.com/thmb/Fi_FEyVa3_-_uzfXh6OdLrzal2M=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/the-best-caesar-salad-recipe-06-40e70f549ba2489db09355abd62f79a9.jpg", "Lunch");
        insertIntoFoods(sqLiteDatabase, "Burger and Fries", "Our signature burger with lettuce, tomato, onion, and pickles on a toasted bun. Served with fries.", "$12.99", "https://thumbs.dreamstime.com/b/burger-french-fries-basket-tartan-tablecloth-ketchup-mustard-bottle-background-close-up-135319836.jpg", "Lunch");
        insertIntoFoods(sqLiteDatabase, "Fish and Chips", "Beer-battered cod fillets served with fries, coleslaw, and tartar sauce.", "$13.99", "https://www.thespruceeats.com/thmb/k8Ejnb3LR7yrhwGirJEC2x6r1sg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/best-fish-and-chips-recipe-434856-Hero-5b61b89346e0fb00500f2141.jpg", "Lunch");
        insertIntoFoods(sqLiteDatabase, "Veggie Wrap", "Grilled portobello mushrooms, roasted red peppers, zucchini, squash, and goat cheese wrapped in a spinach tortilla. Served with a side salad.", "$10.99", "https://www.culinaryhill.com/wp-content/uploads/2020/04/Ultimate-Veggie-Wrap-Recipe-Culinary-Hill-LR-04SQ.jpg", "Lunch");

        insertIntoFoods(sqLiteDatabase, "Grilled Salmon", "Fresh grilled salmon with lemon butter sauce, served with asparagus and mashed potatoes.", "$21.99", "https://www.dinneratthezoo.com/wp-content/uploads/2019/05/grilled-salmon-final-2.jpg", "Dinner");
        insertIntoFoods(sqLiteDatabase, "Steak Frites", "Grilled sirloin steak with a side of crispy fries, served with a side salad.", "$24.99", "https://upload.wikimedia.org/wikipedia/commons/9/9a/Reel_and_Brand_-_September_2021_-_Sarah_Stierch_05.jpg", "Dinner");
        insertIntoFoods(sqLiteDatabase, "Chicken Marsala", "Tender chicken breast in a rich marsala wine sauce, served with garlic mashed potatoes and sautéed green beans.", "$18.99", "https://cafedelites.com/wp-content/uploads/2018/04/Creamy-Chicken-Marsala-IMAGE-21.jpg", "Dinner");
        insertIntoFoods(sqLiteDatabase, "Shrimp Scampi", "Sautéed shrimp in a garlic butter sauce with linguine, served with garlic bread.", "$19.99", "https://assets.bonappetit.com/photos/58a4e12a9fda6d7fbc740e91/6:9/w_2221,h_3332,c_limit/shrimp-scampi.jpg", "Dinner");
        insertIntoFoods(sqLiteDatabase, "Eggplant Parmesan", "Breaded and fried eggplant layered with mozzarella cheese and marinara sauce, served with a side salad.", "$16.99", "https://fitfoodiefinds.com/wp-content/uploads/2021/07/eggplant-parmesan-10-scaled.jpg", "Dinner");

        insertIntoFoods(sqLiteDatabase, "Avocado Toast", "Sourdough toast topped with smashed avocado, cherry tomatoes, red onion, and feta cheese crumbles. Served with a side salad.", "$10.99", "https://simplyfreshfoodie.com/wp-content/uploads/2021/08/DSC_0546.jpg", "Brunch");
        insertIntoFoods(sqLiteDatabase, "Belgian Waffle", "A golden Belgian waffle topped with fresh berries and whipped cream. Served with maple syrup and your choice of bacon or sausage.", "$12.99", "https://storcpdkenticomedia.blob.core.windows.net/media/recipemanagementsystem/media/recipe-media-files/recipes/retail/x17/2020_belgian-style-waffles_16700_760x580.jpg?ext=.jpg", "Brunch");
        insertIntoFoods(sqLiteDatabase, "Smoked Salmon Bagel", "Toasted bagel with cream cheese, smoked salmon, red onion, capers, and fresh dill. Served with a side of mixed greens.", "$14.99", "https://www.thespruceeats.com/thmb/rht67xNHuUXIu8hLkG6_6B7jpqU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/open-face-smoked-salmon-bagel-101094-hero-01-ea26c2ca36af4577b1d40e0af807754b.jpg", "Brunch");
        insertIntoFoods(sqLiteDatabase, "Breakfast Burrito", "Scrambled eggs, black beans, cheddar cheese, and salsa wrapped in a flour tortilla. Served with a side of hash browns.", "$11.99", "https://images-gmi-pmc.edge-generalmills.com/9aaa5c61-860a-427f-a745-b5221f6b909e.jpg", "Brunch");
        insertIntoFoods(sqLiteDatabase, "Eggs Florentine", "Two poached eggs on an English muffin with sautéed spinach and hollandaise sauce. Served with hash browns.", "$13.99", "https://tastesbetterfromscratch.com/wp-content/uploads/2014/04/Eggs-Florentine-9.jpg", "Brunch");

        insertIntoFoods(sqLiteDatabase, "Margarita", "Tequila, triple sec, lime juice, and agave syrup shaken with ice and served in a salt-rimmed glass.", "$8.99", "https://www.seriouseats.com/thmb/rkmijvOtxOQyH3D8n2q8uc67XNk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2015__04__20150323-cocktails-vicky-wasik-margarita-c84b154e757d43688de15dc8f8ca0de9.jpg", "Drinks");
        insertIntoFoods(sqLiteDatabase, "Old Fashioned", "Bourbon, simple syrup, and bitters served over ice with an orange twist.", "$10.99", "https://www.simplyrecipes.com/thmb/s_de1Nuw4ULiHNECVHOCBY5u5Wk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2020__01__Old-Fashioned-Cocktail-LEAD-5-1024x681-aa81a798a156453d80d1f7d41de893ff.jpg", "Drinks");
        insertIntoFoods(sqLiteDatabase, "Mojito", "White rum, fresh mint leaves, lime juice, and simple syrup muddled together and topped with soda water.", "$9.99", "https://kitchenswagger.com/wp-content/uploads/2020/07/mojito-recipe3.jpg", "Drinks");
        insertIntoFoods(sqLiteDatabase, "Gin and Tonic", "Gin, tonic water, and a wedge of lime served over ice.", "$8.99", "https://www.liquor.com/thmb/sYX_sTKUpyagRermLA31SMLF3-8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__liquor__2019__09__18090535__Gin-and-Tonic-720x720-recipe-c2e32c4cf53c4ed7a4de20af8e862a12.jpg", "Drinks");
        insertIntoFoods(sqLiteDatabase, "White Russian", "Vodka, Kahlua, and heavy cream served over ice.", "$9.99", "https://www.thespruceeats.com/thmb/4-cl74JRvv_E16iFHJTpwTG7zlA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/white-russian-recipe-761274-Hero_02-e1b64f0eac1f4b94b9dbe94fc66d83a8.jpg", "Drinks");


        insertIntoFoods(sqLiteDatabase, "Classic Cheesecake", "Creamy New York-style cheesecake with a graham cracker crust. Served plain or with your choice of topping.", "$7.99", "https://i2.wp.com/completelydelicious.com/wp-content/uploads/2020/04/classic-cheesecake-12.jpg", "Desserts");
        insertIntoFoods(sqLiteDatabase, "Chocolate Lava Cake", "Warm chocolate cake with a molten center. Served with vanilla ice cream.", "$8.99", "https://www.foodnetwork.com/content/dam/images/food/fullset/2014/2/19/1/WU0701H_Molten-Chocolate-Cakes_s4x3.jpg", "Desserts");
        insertIntoFoods(sqLiteDatabase, "Apple Pie", "Homemade apple pie with a flaky crust. Served with a scoop of vanilla ice cream.", "$6.99", "https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Apple-Pie_EXPS_MRRA22_6086_E11_03_1b_v3.jpg", "Desserts");
        insertIntoFoods(sqLiteDatabase, "Tiramisu", "Italian dessert made with layers of ladyfingers, espresso, mascarpone cheese, and cocoa powder.", "$9.99", "https://static.onecms.io/wp-content/uploads/sites/43/2022/04/07/21412-tiramisu-ii-3x2-119.jpg", "Desserts");
        insertIntoFoods(sqLiteDatabase, "Crème Brûlée", "Classic French dessert consisting of a rich custard base topped with a layer of caramelized sugar.", "$7.99", "https://www.livewellbakeoften.com/wp-content/uploads/2019/02/Homemade-Creme-Brulee-9.jpg", "Desserts");

        insertIntoFoods(sqLiteDatabase, "Kids Burger", "A juicy burger patty with melted American cheese on a sesame seed bun. Served with fries and a small drink.", "$6.99", "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-563469_10-ecc2be0.jpg", "Kids Menu");
        insertIntoFoods(sqLiteDatabase, "Grilled Cheese", "Melted American cheese on your choice of bread. Served with fries and a small drink.", "$5.99", "https://blog.directauto.com/wp-content/uploads/2018/02/grilled-cheese.jpg", "Kids Menu");
        insertIntoFoods(sqLiteDatabase, "Chicken Tenders", "Breaded chicken tenders served with your choice of dipping sauce. Served with fries and a small drink.", "$7.99", "https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Contest-Winning-Crispy-Chicken-Fingers_exps45596_SD1785596D35B_RMS.jpg", "Kids Menu");
        insertIntoFoods(sqLiteDatabase, "Mac and Cheese", "Creamy macaroni and cheese made with real cheddar cheese. Served with a small drink.", "$5.99", "https://www.blessthismessplease.com/wp-content/uploads/2018/11/stovetop-homemade-macaroni-and-cheese-6-of-6.jpg", "Kids Menu");
        insertIntoFoods(sqLiteDatabase, "Mini Corn Dogs", "Mini hot dogs wrapped in cornmeal batter and fried until golden brown. Served with fries and a small drink.", "$6.99", "https://www.justataste.com/wp-content/uploads/2015/06/best-mini-corn-dogs.jpg", "Kids Menu");
    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {

    }
}
